### ISSUE TITLE
1.21.3 support

### ISSUE THREAD

**Issue by cupang-afk** [pseudoforceyt/PlayerBiomes#5]
as title written

```log
> papi parse cupang_afk %playerbiomes_biome_formatted%
[18:15:24 WARN]: Unexpected exception while parsing console command "papi parse cupang_afk %playerbiomes_biome_formatted%"
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.11.7-DEV-200
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:178) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1029) ~[purpur-1.21.3.jar:1.21.3-2356-03062a8]
        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:1014) ~[purpur-1.21.3.jar:1.21.3-2356-03062a8]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:545) ~[purpur-1.21.3.jar:1.21.3-2356-03062a8]
        at net.minecraft.server.dedicated.DedicatedServer.tickConnection(DedicatedServer.java:494) ~[purpur-1.21.3.jar:1.21.3-2356-03062a8]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1937) ~[purpur-1.21.3.jar:1.21.3-2356-03062a8]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1710) ~[purpur-1.21.3.jar:1.21.3-2356-03062a8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1369) ~[purpur-1.21.3.jar:1.21.3-2356-03062a8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344) ~[purpur-1.21.3.jar:1.21.3-2356-03062a8]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R1/CraftServer
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.jefflib.internal.nms.v1_21.NMSBiomeUtils.getBiomeRegistry(NMSBiomeUtils.java:52) ~[PlayerBiomes [6.0.1].jar:?]
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.jefflib.internal.nms.v1_21.NMSBiomeUtils.getBiomeKey(NMSBiomeUtils.java:47) ~[PlayerBiomes [6.0.1].jar:?]
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.jefflib.internal.nms.v1_21.NMSBiomeUtils.getBiomeName(NMSBiomeUtils.java:42) ~[PlayerBiomes [6.0.1].jar:?]
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.jefflib.internal.nms.v1_21.NMSHandler.getBiomeName(NMSHandler.java:191) ~[PlayerBiomes [6.0.1].jar:?]
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.jefflib.BiomeUtils.getBiomeNamespacedKey(BiomeUtils.java:48) ~[PlayerBiomes [6.0.1].jar:?]
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.PlayerBiomes.getBiomeFormatted(PlayerBiomes.java:22) ~[PlayerBiomes [6.0.1].jar:?]
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.PlayerBiomes.lambda$onEnable$3(PlayerBiomes.java:82) ~[PlayerBiomes [6.0.1].jar:?]
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.jefflib.pluginhooks.PlaceholderAPIHandler$AnonymousPlaceholderExpansion.onRequest(PlaceholderAPIHandler.java:97) ~[PlayerBiomes [6.0.1].jar:?]
        at PlaceholderAPI [2.11.7-DEV-200].jar/me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI [2.11.7-DEV-200].jar:?]
        at PlaceholderAPI [2.11.7-DEV-200].jar/me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI [2.11.7-DEV-200].jar:?]
        at PlaceholderAPI [2.11.7-DEV-200].jar/me.clip.placeholderapi.commands.impl.local.CommandParse.evaluateParseSingular(CommandParse.java:118) ~[PlaceholderAPI [2.11.7-DEV-200].jar:?]
        at PlaceholderAPI [2.11.7-DEV-200].jar/me.clip.placeholderapi.commands.impl.local.CommandParse.evaluate(CommandParse.java:57) ~[PlaceholderAPI [2.11.7-DEV-200].jar:?]
        at PlaceholderAPI [2.11.7-DEV-200].jar/me.clip.placeholderapi.commands.PlaceholderCommandRouter.onCommand(PlaceholderCommandRouter.java:114) ~[PlaceholderAPI [2.11.7-DEV-200].jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R1.CraftServer
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.jefflib.internal.nms.v1_21.NMSBiomeUtils.getBiomeRegistry(NMSBiomeUtils.java:52) ~[PlayerBiomes [6.0.1].jar:?]
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.jefflib.internal.nms.v1_21.NMSBiomeUtils.getBiomeKey(NMSBiomeUtils.java:47) ~[PlayerBiomes [6.0.1].jar:?]
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.jefflib.internal.nms.v1_21.NMSBiomeUtils.getBiomeName(NMSBiomeUtils.java:42) ~[PlayerBiomes [6.0.1].jar:?]
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.jefflib.internal.nms.v1_21.NMSHandler.getBiomeName(NMSHandler.java:191) ~[PlayerBiomes [6.0.1].jar:?]
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.jefflib.BiomeUtils.getBiomeNamespacedKey(BiomeUtils.java:48) ~[PlayerBiomes [6.0.1].jar:?]
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.PlayerBiomes.getBiomeFormatted(PlayerBiomes.java:22) ~[PlayerBiomes [6.0.1].jar:?]
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.PlayerBiomes.lambda$onEnable$3(PlayerBiomes.java:82) ~[PlayerBiomes [6.0.1].jar:?]
        at PlayerBiomes [6.0.1].jar/com.pseudosmp.PlayerBiomes.jefflib.pluginhooks.PlaceholderAPIHandler$AnonymousPlaceholderExpansion.onRequest(PlaceholderAPIHandler.java:97) ~[PlayerBiomes [6.0.1].jar:?]
        at PlaceholderAPI [2.11.7-DEV-200].jar/me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI [2.11.7-DEV-200].jar:?]
        at PlaceholderAPI [2.11.7-DEV-200].jar/me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI [2.11.7-DEV-200].jar:?]
        at PlaceholderAPI [2.11.7-DEV-200].jar/me.clip.placeholderapi.commands.impl.local.CommandParse.evaluateParseSingular(CommandParse.java:118) ~[PlaceholderAPI [2.11.7-DEV-200].jar:?]
        at PlaceholderAPI [2.11.7-DEV-200].jar/me.clip.placeholderapi.commands.impl.local.CommandParse.evaluate(CommandParse.java:57) ~[PlaceholderAPI [2.11.7-DEV-200].jar:?]
        at PlaceholderAPI [2.11.7-DEV-200].jar/me.clip.placeholderapi.commands.PlaceholderCommandRouter.onCommand(PlaceholderCommandRouter.java:114) ~[PlaceholderAPI [2.11.7-DEV-200].jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        ... 10 more
```

**Comment by cupang-afk** [comment]
close this issue cuz it seem already fixed in 6.0.2

sorry man, i only check your github releases

well have a nice day
